seed: 42
data_dir: "data/raw"
splits_dir: "data/interim"
output_dir: "outputs"
models_dir: "models"

task: "levels3"   # "levels3" o "classes10"
class_map_3:
  0: ["c0"]
  1: ["c2", "c3", "c4", "c9"]        # moderada (sin c1)
  2: ["c1", "c5", "c6", "c7", "c8"]  # alta (ahora incluye c1)
class_map_10:
  c0: 0
  c1: 1
  c2: 2
  c3: 3
  c4: 4
  c5: 5
  c6: 6
  c7: 7
  c8: 8
  c9: 9

image_size: 128        # reducimos resolución de 224 → 128
batch_size: 8          # bajamos el tamaño del batch para CPU
num_workers: 2         # menos hilos, evita sobrecarga

train:
  epochs: 2            # mantenemos 2 épocas para ver rendimiento
  lr: 0.0003
  weight_decay: 0.0001
  scheduler: cosine


augmentations:
  train:
    - "Resize:256"
    - "RandomResizedCrop:224"
    - "HorizontalFlip:0.5"
    - "ColorJitter:0.2"
    - "MotionBlur:0.2"
  val:
    - "Resize:256"
    - "CenterCrop:224"

split:
  strategy: "grouped"
  val_size: 0.15
  test_size: 0.15
  group_key: "driver_id"
